// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pizza-pub/PizzaPubProfile.tsx": () => import("../components/mockups/pizza-pub/PizzaPubProfile.tsx"),
  "./components/mockups/pizza-world-galaxy/PizzaWorldGalaxy.tsx": () => import("../components/mockups/pizza-world-galaxy/PizzaWorldGalaxy.tsx")
};
